#!/usr/bin/python
# Example using a character LCD connected to a Raspberry Pi or BeagleBone Black.
import math
import Adafruit_CharLCD as LCD
import Adafruit_BBIO.GPIO as GPIO
import time


# BeagleBone Black configuration:
lcd_rs        = 'P8_8'
lcd_en        = 'P8_10'
lcd_d4        = 'P8_18'
lcd_d5        = 'P8_16'
lcd_d6        = 'P8_14'
lcd_d7        = 'P8_12'
lcd_backlight = 'P8_7'

# Define LCD column and row size for 16x2 LCD.
lcd_columns = 16
lcd_rows    = 2

# Alternatively specify a 20x4 LCD.
# lcd_columns = 20
# lcd_rows    = 4

# Initialize the LCD using the pins above.
lcd = LCD.Adafruit_CharLCD(lcd_rs, lcd_en, lcd_d4, lcd_d5, lcd_d6, lcd_d7,
                                                        lcd_columns, lcd_rows, lcd_b$

def basextodec(base,number):
    bstr = str(number)
    power = len(bstr)-1
    decimal = 0
    for i in bstr:
        i = int(i)
        decimal += i*(base**power)
        power -= 1
    print (decimal)
    decimal = str(decimal)
    value = str(number)
    lcd.clear()
    lcd.message(decimal+"   "+value)
def dectobasex(dec,base):
    number = ""
    while (dec != 0):
        dec1 = dec%base
        dec2 = dec/base
        dec = int(dec2)
        app = str(dec1)
        number = app +" "+ number
    print (number)
    return number
#defining varables
value = ['','','']
value2 = '00'
#sets the GPIO to an input
GPIO.setup("P8_39", GPIO.IN)
GPIO.setup("P8_40", GPIO.IN)
GPIO.setup("P8_17", GPIO.IN)
GPIO.setup("P8_15", GPIO.IN)
GPIO.setup("P8_13", GPIO.IN)
GPIO.setup("P8_11", GPIO.IN)

#reads the state of all the switches
def Main():
        while True:
            #reads the state of switch 1
                if GPIO.input("P8_39") and not GPIO.input("P8_40"):
                                value[0] = '0'
                                value1 = ''.join(value)
                                print (value1)
                if not GPIO.input("P8_39") and GPIO.input("P8_40"):
                                value[0] = '2'
                                value1 = ''.join(value)
                                print (value1)
                if not GPIO.input("P8_39") and not GPIO.input("P8_40"):
                                value[0] = '1'
                                value1 = ''.join(value)
                                print (value1)
            #reads the state of switch 2
                if GPIO.input("P8_15") and not GPIO.input("P8_17"):
                                value[1] = '0'
                                value1 = ''.join(value)
                                print (value1)
                if not GPIO.input("P8_15") and GPIO.input("P8_17"):
                                value[1] = '2'
                                value1 = ''.join(value)
                                print (value1)
                if not GPIO.input("P8_15") and not GPIO.input("P8_17"):
                                value[1] = '1'
                                value1 = ''.join(value)
                                print (value1)
                if value1 != value2:
                        value2 = value1
                        basextodec(3,value2)

#runs the switch function
Main()

